use crate::structure::{
    effective_choice_alternatives, effective_record_fields, project_structural_type,
};
use ams_gra_oms_ir::{QualifiedName, SchemaIr, TypeDecl, TypeKind, TypeRef, TypeRefTarget};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

/// A closed, schema-known by-value representation of an abstract structural declaration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AbstractValueProjection<'a> {
    pub declaration: &'a TypeDecl,
    /// Concrete transitive descendants in original Schema IR order.
    pub concrete_descendants: Vec<&'a TypeDecl>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AbstractValueProjectionError {
    MissingDeclaration(QualifiedName),
    NonStructuralTarget(QualifiedName),
    NonAbstractTarget(QualifiedName),
    NoConcreteDescendants(QualifiedName),
}

/// Closed-value topology of a demanded abstract structural value.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AbstractValueTopology<'a> {
    Acyclic(AbstractValueProjection<'a>),
    NoConcreteDescendants(QualifiedName),
    RecursiveValueGraph { cycle: Vec<QualifiedName> },
}

impl fmt::Display for AbstractValueProjectionError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingDeclaration(name) => write!(f, "missing declaration {}", name.local_name),
            Self::NonStructuralTarget(name) => {
                write!(
                    f,
                    "abstract value target {} is non-structural",
                    name.local_name
                )
            }
            Self::NonAbstractTarget(name) => {
                write!(
                    f,
                    "abstract value target {} is not abstract",
                    name.local_name
                )
            }
            Self::NoConcreteDescendants(name) => write!(
                f,
                "abstract value target {} has no concrete structural descendants",
                name.local_name
            ),
        }
    }
}

impl std::error::Error for AbstractValueProjectionError {}

/// Project every concrete transitive structural descendant of an abstract target.
///
/// Abstract intermediates are ancestry metadata and are intentionally not variants.
pub fn project_abstract_value<'a>(
    schema: &'a SchemaIr,
    target: &QualifiedName,
) -> Result<AbstractValueProjection<'a>, AbstractValueProjectionError> {
    let declaration = schema
        .types
        .iter()
        .find(|declaration| declaration.name == *target)
        .ok_or_else(|| AbstractValueProjectionError::MissingDeclaration(target.clone()))?;
    if !is_structural(declaration) {
        return Err(AbstractValueProjectionError::NonStructuralTarget(
            target.clone(),
        ));
    }
    if !declaration.is_abstract {
        return Err(AbstractValueProjectionError::NonAbstractTarget(
            target.clone(),
        ));
    }

    let mut descendants = Vec::new();
    for candidate in &schema.types {
        if candidate.is_abstract || !is_structural(candidate) || candidate.name == *target {
            continue;
        }
        let Ok(projection) = project_structural_type(schema, &candidate.name) else {
            continue;
        };
        if projection
            .ancestry
            .iter()
            .any(|level| level.declaration.name == *target)
        {
            descendants.push(candidate);
        }
    }
    if descendants.is_empty() {
        return Err(AbstractValueProjectionError::NoConcreteDescendants(
            target.clone(),
        ));
    }
    Ok(AbstractValueProjection {
        declaration,
        concrete_descendants: descendants,
    })
}

/// Project an abstract structural named value reference, if it needs a
/// generated closed-sum wrapper. Other named references retain their exact
/// existing named-value representation.
pub fn abstract_value_projection_for_ref<'a>(
    schema: &'a SchemaIr,
    type_ref: &TypeRef,
) -> Result<Option<AbstractValueProjection<'a>>, AbstractValueProjectionError> {
    let TypeRefTarget::Named(target) = &type_ref.target else {
        return Ok(None);
    };
    let declaration = schema
        .types
        .iter()
        .find(|declaration| declaration.name == *target)
        .ok_or_else(|| AbstractValueProjectionError::MissingDeclaration(target.clone()))?;
    if declaration.is_abstract && is_structural(declaration) {
        project_abstract_value(schema, target).map(Some)
    } else {
        Ok(None)
    }
}

/// Classify generated by-value topology for an abstract wrapper without
/// conflating structural ancestry with containment.
pub fn classify_abstract_value_topology<'a>(
    schema: &'a SchemaIr,
    target: &QualifiedName,
) -> Result<AbstractValueTopology<'a>, AbstractValueProjectionError> {
    let projection = match project_abstract_value(schema, target) {
        Ok(projection) => projection,
        Err(AbstractValueProjectionError::NoConcreteDescendants(name)) => {
            return Ok(AbstractValueTopology::NoConcreteDescendants(name));
        }
        Err(error) => return Err(error),
    };
    let targets = abstract_value_targets(schema)
        .into_iter()
        .map(|declaration| declaration.name.clone())
        .collect::<BTreeSet<_>>();
    let mut visiting = Vec::new();
    let mut visited = BTreeSet::new();
    if let Some(cycle) =
        visit_generated_value(schema, target, &targets, &mut visiting, &mut visited)?
    {
        return Ok(AbstractValueTopology::RecursiveValueGraph { cycle });
    }
    Ok(AbstractValueTopology::Acyclic(projection))
}

fn visit_generated_value(
    schema: &SchemaIr,
    name: &QualifiedName,
    wrappers: &BTreeSet<QualifiedName>,
    visiting: &mut Vec<QualifiedName>,
    visited: &mut BTreeSet<QualifiedName>,
) -> Result<Option<Vec<QualifiedName>>, AbstractValueProjectionError> {
    if let Some(position) = visiting.iter().position(|candidate| candidate == name) {
        let mut cycle = visiting[position..].to_vec();
        cycle.push(name.clone());
        return Ok(Some(cycle));
    }
    if !visited.insert(name.clone()) {
        return Ok(None);
    }
    visiting.push(name.clone());
    let declaration = schema
        .types
        .iter()
        .find(|candidate| candidate.name == *name)
        .ok_or_else(|| AbstractValueProjectionError::MissingDeclaration(name.clone()))?;
    let dependencies = if wrappers.contains(name) {
        match project_abstract_value(schema, name) {
            Ok(projection) => projection
                .concrete_descendants
                .into_iter()
                .map(|candidate| candidate.name.clone())
                .collect(),
            Err(AbstractValueProjectionError::NoConcreteDescendants(_)) => Vec::new(),
            Err(error) => return Err(error),
        }
    } else {
        match declaration.kind {
            TypeKind::Record { .. } => effective_record_fields(schema, name)
                .ok()
                .into_iter()
                .flatten()
                .filter_map(|field| named(&field.type_ref))
                .collect(),
            TypeKind::Choice { .. } => effective_choice_alternatives(schema, name)
                .ok()
                .into_iter()
                .flatten()
                .filter_map(|field| named(&field.type_ref))
                .collect(),
            TypeKind::Alias(ref reference) => named(reference).into_iter().collect(),
            TypeKind::List { ref item_type, .. } => named(item_type).into_iter().collect(),
            TypeKind::Primitive(_) | TypeKind::Enumeration { .. } => Vec::new(),
        }
    };
    for dependency in dependencies {
        if let Some(cycle) =
            visit_generated_value(schema, &dependency, wrappers, visiting, visited)?
        {
            return Ok(Some(cycle));
        }
    }
    visiting.pop();
    Ok(None)
}

fn named(reference: &TypeRef) -> Option<QualifiedName> {
    match &reference.target {
        TypeRefTarget::Named(name) => Some(name.clone()),
        TypeRefTarget::Primitive(_) => None,
    }
}

/// Return abstract structural declarations occurring in named value positions.
///
/// A base-type relationship is intentionally excluded. Results preserve Schema IR order.
pub fn abstract_value_targets(schema: &SchemaIr) -> Vec<&TypeDecl> {
    let declarations = schema
        .types
        .iter()
        .map(|declaration| (declaration.name.clone(), declaration))
        .collect::<BTreeMap<_, _>>();
    let mut targets = BTreeSet::new();
    for declaration in &schema.types {
        match &declaration.kind {
            TypeKind::Record { fields } => fields.iter().for_each(|field| {
                collect_abstract_target(&declarations, &field.type_ref, &mut targets);
            }),
            TypeKind::Choice { alternatives } => alternatives.iter().for_each(|alternative| {
                collect_abstract_target(&declarations, &alternative.type_ref, &mut targets);
            }),
            TypeKind::Alias(target) => collect_abstract_target(&declarations, target, &mut targets),
            TypeKind::List { item_type, .. } => {
                collect_abstract_target(&declarations, item_type, &mut targets);
            }
            TypeKind::Primitive(_) | TypeKind::Enumeration { .. } => {}
        }
    }
    for message in &schema.messages {
        collect_abstract_target(&declarations, &message.payload_type, &mut targets);
    }
    schema
        .types
        .iter()
        .filter(|declaration| targets.contains(&declaration.name))
        .collect()
}

fn collect_abstract_target(
    declarations: &BTreeMap<QualifiedName, &TypeDecl>,
    type_ref: &TypeRef,
    targets: &mut BTreeSet<QualifiedName>,
) {
    let TypeRefTarget::Named(name) = &type_ref.target else {
        return;
    };
    if declarations
        .get(name)
        .is_some_and(|declaration| declaration.is_abstract && is_structural(declaration))
    {
        targets.insert(name.clone());
    }
}

pub(crate) fn is_structural(declaration: &TypeDecl) -> bool {
    matches!(
        declaration.kind,
        TypeKind::Record { .. } | TypeKind::Choice { .. }
    )
}
