<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:t="urn:test:integral" xmlns:uci="https://www.vdl.afrl.af.mil/programs/oam" targetNamespace="urn:test:integral" elementFormDefault="qualified">
  <xs:simpleType name="Serial"><xs:restriction base="xs:int"><xs:minInclusive value="1"/><xs:maxInclusive value="999"/><xs:pattern value="[0-9]{1,3}"/></xs:restriction></xs:simpleType>
  <xs:simpleType name="Renamed"><xs:restriction base="xs:int"><xs:minInclusive value="1"/><xs:maxInclusive value="999"/><xs:pattern value="[0-9]{1,3}"/></xs:restriction></xs:simpleType>
  <xs:complexType name="Payload"><xs:sequence>
    <xs:element name="Required" type="t:Serial"/>
    <xs:element name="Optional" type="t:Renamed" minOccurs="0"/>
    <xs:element name="Repeated" type="t:Serial" minOccurs="0" maxOccurs="3"/>
    <xs:element name="Selection" type="t:Pick"/>
    <xs:element name="Item" type="t:AbstractValue"/>
  </xs:sequence></xs:complexType>
  <xs:complexType name="Pick"><xs:choice><xs:element name="Number" type="t:Serial"/><xs:element name="Text" type="xs:string"/></xs:choice></xs:complexType>
  <xs:complexType name="AbstractValue" abstract="true"><xs:sequence/></xs:complexType>
  <xs:complexType name="ConcreteValue"><xs:complexContent><xs:extension base="t:AbstractValue"><xs:sequence><xs:element name="Number" type="t:Serial"/></xs:sequence></xs:extension></xs:complexContent></xs:complexType>
  <xs:element name="Message" type="t:Payload" uci:version="000.000.000.000"/>
</xs:schema>