<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:t="urn:test:time" xmlns:uci="https://www.vdl.afrl.af.mil/programs/oam" targetNamespace="urn:test:time" elementFormDefault="qualified">
  <xs:simpleType name="Clock"><xs:restriction base="xs:time"><xs:pattern value=".+Z"/></xs:restriction></xs:simpleType>
  <xs:complexType name="Base"><xs:sequence><xs:element name="Required" type="t:Clock"/></xs:sequence></xs:complexType>
  <xs:complexType name="Payload"><xs:complexContent><xs:extension base="t:Base"><xs:sequence>
    <xs:element name="Optional" type="t:Clock" minOccurs="0"/>
    <xs:element name="Bounded" type="t:Clock" minOccurs="0" maxOccurs="3"/>
    <xs:element name="Unbounded" type="t:Clock" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="Selection" type="t:Pick"/>
    <xs:element name="Item" type="t:AbstractClock"/>
  </xs:sequence></xs:extension></xs:complexContent></xs:complexType>
  <xs:complexType name="Pick"><xs:choice><xs:element name="Time" type="t:Clock"/><xs:element name="Text" type="xs:string"/></xs:choice></xs:complexType>
  <xs:complexType name="AbstractClock" abstract="true"><xs:sequence/></xs:complexType>
  <xs:complexType name="ConcreteClock"><xs:complexContent><xs:extension base="t:AbstractClock"><xs:sequence><xs:element name="Time" type="t:Clock"/></xs:sequence></xs:extension></xs:complexContent></xs:complexType>
  <xs:complexType name="Unrelated"><xs:sequence><xs:element name="Text" type="xs:string"/></xs:sequence></xs:complexType>
  <xs:complexType name="EmptyClock" abstract="true"><xs:sequence><xs:element name="Time" type="t:Clock" minOccurs="0"/></xs:sequence></xs:complexType>
  <xs:complexType name="AbsentHolder"><xs:sequence><xs:element name="Absent" type="t:EmptyClock" minOccurs="0"/></xs:sequence></xs:complexType>
  <xs:element name="Message" type="t:Payload" uci:version="000.000.000.000"/>
</xs:schema>